# Rustfmt configuration for consistent code formatting
edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true 